### ISSUE TITLE
Support derived addresses

### ISSUE THREAD

**Issue by MrStahlfelge** [ergoplatform/ergo-wallet-android#10]
Derived addresses need to be supported. 

## Wallet screen
- [X] Balance etc shows total amount of all addresses. 
- [x] Same tokens on different addresses should be shown as a single entry.

## New wallet details screen
- [X] Tapping on a wallet card on the wallets overview will switch to the wallet details screen. 
- [x] This screen lists all already derived addresses with balance, tokens etc. 
- [X] Addresses can be labeled (useful for saving pots etc). 
- [x] Addresses can be selected to switch to send or receive screen. 
- [X] There is a button to create new derived addresses. 
- [X] There is also a way to navigate to the wallet settings screen from here.

## Send screen
- [x] A way to select the actual address an amount should be sent from has to be added. Additionally, there could be an "sent from all" item (like Yoroi does)

## Receive screen
- [x] A way to select the actual address an amount should be sent to has to be added.

## Wallet creation screen
- [x] #39

## Database
- [X] New table wallet_addresses with wallet_id, address, label, derivation_idx
- [X] Main (zero index) address will stay in wallet_config, wallet balances can get stored in wallet_state without any changes.

## Open questions
- [X] How to integrate this feature with read-only wallets? => #32 
- [X] Is[ change amount transferred to first derived address or first selected derived address](https://github.com/ergoplatform/ergo-appkit/blob/dd40e4e5f4d4423181cf50a66382266250a5461e/lib-api/src/main/java/org/ergoplatform/appkit/BoxOperations.java#L153)?

**Comment by Alisovsky** [comment]
> How to integrate this feature with read-only wallets?

I think that you can, instead of asking for address, ask for an extended public key on read-only wallet creation and then derive addresses from that. On this paper wallet I'm working on, there is an extended pk exactly for this purpose. Also, Yoroi does it too.

**Comment by anon-br** [comment]
> How to integrate this feature with read-only wallets?

I think that you can, instead of asking for address, ask for an extended public key on read-only wallet creation and then derive addresses from that. On this paper wallet I'm working on, there is an extended pk exactly for this purpose. Also, Yoroi does it too.
