### ISSUE TITLE
Feature request - give Copy Address button haptic feedback 

### ISSUE THREAD

**Issue by ghost** [ergoplatform/ergo-wallet-android#157]
On iOS - could you make the Copy Receive Address button responsive, so once it is clicked - you would feel it (haptic?). Also - and perhaps more importantly, when you click - it would immediately copy the address and a pop up will say "copied"

**Comment by MrStahlfelge** [comment]
Great idea. There is a lot of copy address functionality in different screens, can you specify which ones are you referring to?

**Comment by MrStahlfelge** [comment]
Haptic feedback on iOS: https://github.com/signalapp/Signal-iOS/blob/abbb0ecdefaf158eabe0bd3616c49e5e949dbda5/SignalMessaging/utils/HapticFeedback.swift
