### ISSUE TITLE
v2.3.2225 does not work on M1 macs

### ISSUE THREAD

**Issue by achaiah** [ergoplatform/ergo-wallet-android#166]
I get an error when running this on M1 mac: 
`Caused by: org.jetbrains.skiko.LibraryLoadException: Cannot find libskiko-macos-arm64.dylib.sha256, proper native dependency missing.
	at org.jetbrains.skiko.Library.findAndLoad(Library.kt:105)
	at org.jetbrains.skiko.Library.load(Library.kt:59)
	at org.jetbrains.skia.impl.Library$Companion.staticLoad(Library.jvm.kt:12)
	at org.jetbrains.skia.Image.<clinit>(Image.kt:144)`

Cursory internet search seems to indicate that the Kotlin version needs to be updated before compiling: https://stackoverflow.com/questions/70150052/org-jetbrains-skiko-libraryloadexception-cannot-find-libskiko-macos-arm64-dylib

**Comment by MrStahlfelge** [comment]
There is no macos-arm compile available, hence it does not work. You have to run it in compatibility mode (rosetta) with an amd64 jvm.

**Comment by MrStahlfelge** [comment]
Reason is that there are (or were) no skia deps available for macos-arm
