### ISSUE TITLE
Unable to Send Coins or View Seed Phrase but Can Access Wallet

### ISSUE THREAD

**Issue by DBCoderAtLarge** [ergoplatform/ergo-wallet-android#172]
I am able to open the wallet on my Android phone, but I cannot access the seed phrase, or even send coins to another wallet.
`security error: Only security key is supported`

The finger print input gives the same error. If the PIN is the access PIN for the phone, why can I not access my coins? I can unlock my phone.

As some background, I changed the PIN at some point due to a work commitment. But I have since changed it back to what it was. But surely that should not matter.

Thanks

**Comment by MrStahlfelge** [comment]
When the secrets were encrypted with device security (biometrics), the encryption keys are deleted whenever device authentication is changed for security reasons. Changing back to the former PIN does not help as the keys are deleted.

You need to restore the wallet from your seed phrase.

**Comment by DBCoderAtLarge** [comment]
So, my funds are gone because I changed my device PIN. That's a bit of a hellish loophole. Yeah, I can't locate the seed phrase for this wallet. I finally decided to do something about that, when my attempt to send funds failed.

**Comment by MrStahlfelge** [comment]
No, the funds are gone because you did not write down the seed phrase and store it in a safe place despite confirming to do so when creating the wallet.
Closing this as there's nothing that can be done here.
