### ISSUE TITLE
ErgoAuthRequest does not match EIP-0028 data format

### ISSUE THREAD

**Issue by altwright** [ergoplatform/ergo-wallet-android#184]
I've been testing ErgoAuth using the Ergo Wallet app and I have noticed that the expected ErgoAuthRequest JSON key "replyTo" in the below line...

https://github.com/ergoplatform/ergo-wallet-app/blob/ed48739f9fb3a2ab6fe3346be8808deb599f42ad/common-jvm/src/main/java/org/ergoplatform/uilogic/ergoauth/ErgoAuth.kt#L43

... Is different from the key "replyToUrl" as defined in the official documentation for ErgoAuth [here](https://docs.ergoplatform.com/dev/wallet/payments/ergoauth/#response-body-ergoauthrequest) and [here](https://github.com/ergoplatform/eips/blob/ccfe51957f75e24f0750b2813d694bd938851f7e/eip-0028.md#response-body-ergoauthrequest). Has the specification for ErgoAuth changed since these documentation pages were published?

Thanks.

**Comment by MrStahlfelge** [comment]
You are right, looks like I got confused with the name of the internal class member and the json key. It is better to change it in EIP as the existing implementations are all using "replyTo" - feel free to submit a PR.
