### ISSUE TITLE
Lost all Ergo

### ISSUE THREAD

**Issue by Eltoro8** [ergoplatform/ergo-wallet-android#44]
All my Ergo was withdrawn from my account using this wallet

**Comment by MrStahlfelge** [comment]
It seems that the backend has hickups at the moment so the amount shown went to 0 for you which is wrong. If the ERG are really withdawn, there would be a transaction withdrawing the ERG. Is there such a transaction?

**Comment by Eltoro8** [comment]
Thank you for the quick really,
I can't see any transactions and just goes to a scene fetching data, will
the issue be fixed and go back to normal?

Cheers,
Ben

**Comment by MrStahlfelge** [comment]
As soon as ergo explorer is back online the correct balance will be shown again

**Comment by Eltoro8** [comment]
Thank you,

Had me very worried! Hope it's back up soon

Cheers

**Comment by MrStahlfelge** [comment]
It is back up, when the problem is solved for you please close the issue
