### ISSUE TITLE
defect: grammar incorrect "synced 1 minutes ago"

### ISSUE THREAD

**Issue by jayruffing** [ergoplatform/ergo-wallet-android#57]
Given I have a wallet that isn't currently synced
When I have synced 1 minute before current time
Then I see "synced 1 minute ago"
<img width="316" alt="2021-11-20_10-37-10" src="https://user-images.githubusercontent.com/2592500/142736315-e14bd2a5-4794-4ea6-ba21-155c211cceb3.png">

actual result: "synced 1 minutes ago"

English is hard. really

**Comment by MrStahlfelge** [comment]
I am aware of this and just waited for someone to notice. 🤡
Will get changed but not top priority.

**Comment by jayruffing** [comment]
this should be the last thing that gets fixed :)
